apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-aetherroyale-backend-deployment
  namespace: staging-aetherroyale-backend
  labels:
    app: staging-aetherroyale-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-aetherroyale-backend
  template:
    metadata:
      labels:
        app: staging-aetherroyale-backend
    spec:
      containers:
        - name: staging-aetherroyale-backend
          image: corentin35/aetherroyale-backend:staging-${TAG_VERSION}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          resources:
            requests:
              cpu: '10m'
              memory: '160Mi'
            limits:
              cpu: '400m'
              memory: '768Mi'
      imagePullSecrets:
        - name: regcred
