apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-seatyrants-website-backend-deployment
  namespace: prod-seatyrants-website-backend
  labels:
    app: prod-seatyrants-website-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: prod-seatyrants-website-backend
  template:
    metadata:
      labels:
        app: prod-seatyrants-website-backend
    spec:
      containers:
        - name: prod-seatyrants-website-backend
          image: corentin35/seatyrants-website-backend:${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          env:
            - name: PORT
              value: '3333'
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "768Mi"
      imagePullSecrets:
        - name: regcred
