apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-seatyrants-website-backend-hpa
  namespace: prod-seatyrants-website-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-seatyrants-website-backend-deployment
  minReplicas: 6
  maxReplicas: 30
  targetCPUUtilizationPercentage: 50
