export type RCNETSimulationEtatMetrics = {
  frequence_cible_tick_simulation_hz: number
  frequence_reelle_tick_simulation_hz_sur_derniere_seconde: number
  nombre_ticks_simulation_executes_sur_derniere_seconde: number
  temps_moyen_par_tick_sur_derniere_seconde_ms: number
  temps_en_ms_sous_lequel_se_situent_95_pourcent_des_ticks_sur_les_deux_dernieres_secondes: number
  temps_en_ms_sous_lequel_se_situent_99_pourcent_des_ticks_sur_les_deux_dernieres_secondes: number
  temps_maximum_observe_pour_un_tick_sur_derniere_seconde_ms: number
  identifiant_tick_du_temps_maximum_observe_sur_derniere_seconde: number
  retard_moyen_de_reveil_du_thread_parmi_les_ticks_en_retard_sur_derniere_seconde_ms: number
  retard_maximum_observe_sur_derniere_seconde_ms: number
  nombre_de_reveils_du_thread_apres_l_horaire_prevu_sur_derniere_seconde: number
  temps_moyen_total_reel_du_tick_en_comptant_retard_de_reveil_plus_traitement_sur_derniere_seconde_ms: number
  marge_moyenne_restante_avant_de_deborder_sur_le_tick_suivant_sur_derniere_seconde_ms: number
  budget_maximal_par_tick_avant_de_deborder_sur_le_tick_suivant_ms: number
  nombre_ticks_de_rattrapage_executes_sur_derniere_seconde: number
  nombre_abandons_de_backlog_simulation_sur_derniere_seconde: number
}

export type GameserverSimulationEtatMetricsPayload = {
  server_id: number
  temps_reel_traitement_network_incoming_dispatcher_sur_ce_tick_ms: number
  temps_reel_traitement_http_dispatcher_sur_ce_tick_ms: number
  temps_reel_traitement_nats_dispatcher_sur_ce_tick_ms: number
  temps_reel_traitement_check_match_flow_sur_ce_tick_ms: number
  temps_reel_traitement_world_simulate_sur_ce_tick_ms: number
  temps_reel_traitement_create_full_snapshots_sur_ce_tick_ms: number
  simulation_etat_metrics: RCNETSimulationEtatMetrics
}